// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    databaseURL:
        "https://maria-pitanga-e5e82-default-rtdb.europe-west1.firebasedatabase.app",
    apiKey: 'AIzaSyCVQqEw0iJHheG4fyxbdF5k2k2qVkEhXeg',
    appId: '1:780940930307:web:0b59e7cae5540f56e94d36',
    messagingSenderId: '780940930307',
    projectId: 'maria-pitanga-e5e82',
    authDomain: 'maria-pitanga-e5e82.firebaseapp.com',
    storageBucket: 'maria-pitanga-e5e82.firebasestorage.app',
    measurementId: 'G-8EMYZSNR9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    databaseURL:
        "https://maria-pitanga-e5e82-default-rtdb.europe-west1.firebasedatabase.app",
    apiKey: 'AIzaSyBrCT6yAa06vMShUCnF5JXAod6gAQT4RGU',
    appId: '1:780940930307:android:803643cf600ac781e94d36',
    messagingSenderId: '780940930307',
    projectId: 'maria-pitanga-e5e82',
    storageBucket: 'maria-pitanga-e5e82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    databaseURL:
        "https://maria-pitanga-e5e82-default-rtdb.europe-west1.firebasedatabase.app",
    apiKey: 'AIzaSyAwRAJYNcvkAXXaxDs3-ovA-9t5JqYJfsQ',
    appId: '1:780940930307:ios:6d8e8746f42bdf87e94d36',
    messagingSenderId: '780940930307',
    projectId: 'maria-pitanga-e5e82',
    storageBucket: 'maria-pitanga-e5e82.firebasestorage.app',
    iosBundleId: 'pt.workmade.mariaPitanga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    databaseURL:
        "https://maria-pitanga-e5e82-default-rtdb.europe-west1.firebasedatabase.app",
    apiKey: 'AIzaSyAwRAJYNcvkAXXaxDs3-ovA-9t5JqYJfsQ',
    appId: '1:780940930307:ios:6d8e8746f42bdf87e94d36',
    messagingSenderId: '780940930307',
    projectId: 'maria-pitanga-e5e82',
    storageBucket: 'maria-pitanga-e5e82.firebasestorage.app',
    iosBundleId: 'pt.workmade.mariaPitanga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    databaseURL:
        "https://maria-pitanga-e5e82-default-rtdb.europe-west1.firebasedatabase.app",
    apiKey: 'AIzaSyCVQqEw0iJHheG4fyxbdF5k2k2qVkEhXeg',
    appId: '1:780940930307:web:e641cf753d1ea33ce94d36',
    messagingSenderId: '780940930307',
    projectId: 'maria-pitanga-e5e82',
    authDomain: 'maria-pitanga-e5e82.firebaseapp.com',
    storageBucket: 'maria-pitanga-e5e82.firebasestorage.app',
    measurementId: 'G-F5JVZHY6PM',
  );
}
